name: 'Node Continous Integration'

on:
  pull_request:
    branches: ['main']

jobs:
  test_pull_request:
    runs-on: ubunut-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Run compile
        uses: borales/actions-yarn@v4
        with:
          cmd: compile
